name: Unzip Fonts Automatically
on:
  push:
    paths:
      - 'fonts.zip'
jobs:
  unzip-process:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Unzip File
        run: |
          unzip -o fonts.zip
          rm fonts.zip

      - name: Commit and Push Extracted Folders
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add "Cinzel Regular" "Cinzel Bold"
          git commit -m "Extract fonts from zip via Workflow"
          git push
          
